### PR TITLE
Upscale 22x22px icons to 24x24px adding 1px to the edges

### PR DESCRIPTION
**Pull request by rbuj**
Test:

Disable HiDPI
```shell
$ gsettings set org.mate.interface window-scaling-factor 1
```
- Toolbar icons
- File icons in List View on Caja, zoom at 50%:

Screenshot at 2019-08-21 00-31-59

### CODE REVIEW

**Comment by lukefromdc** [comment]
So basically this uses the same icons for 22x22 and 24x24, changing what amounts to the padding (the empty space in the image beyond all visible elements). Thus the image itself should not have to be scaled at all, which on this small difference in size could make a huge  difference in clarity unless both icon sizes are generated directly by scaling down from a much larger svg icon.

**Comment by rbuj** [comment]
@lukefromdc - yes that's right.

**Comment by sc0w** [comment]
@rbuj 

Thanks a lot!

This PR fixes the problems I mentioned in https://github.com/mate-desktop/mate-icon-theme/pull/34#issuecomment-522976633 and https://github.com/mate-desktop/mate-icon-theme/pull/34#issuecomment-523052352

**Comment by sc0w** [comment]
I would like to see this commit in 1.22 branch, I tried but I see conflicts, @rbuj please can you try it? I don't know if more commits are needed.

**Comment by rbuj** [comment]
@sc0w done

**Pull request merged**
