### PR TITLE
rename mate logo

### PR DESCRIPTION
**Pull request by raveit65**
fixes https://github.com/mate-desktop/mate-panel/issues/959
This is tested with fedora 30 and i will use it for fedora builds.
No missing MATE logo in our applications.
I am really in doubt that mate.png is used from a application.
So i offer this to use it for MATE in general.

### CODE REVIEW

**Comment by raveit65** [comment]
I simply renamed the icons in repo.
I didn#t create them new.
Why you think that?

**Comment by raveit65** [comment]
Fixed.

**Comment by vkareh** [comment]
Thanks, this works for me now

**Comment by monsta** [comment]
We could probably just remove that icon if no app uses it. Such app would have problems anyway when any other icon theme would be used - there would be a missing icon...

**Comment by raveit65** [comment]
Yes, please re-check/test for yourself that it isn't needed.

**Pull request merged**
