### PR TITLE
Gen png icons from source - Mate theme

### PR DESCRIPTION
**Pull request by rbuj**
clean & build:
```sh
make -C mate clean-png-icons
make -C mate build-png-icons
```

### CODE REVIEW

**Comment by lukefromdc** [comment]
I found that rebuilding the icons takes a vary long time with this. Is that something that now needs to be done at every build? I don't really understand how this works: are the new icons shipped, or do they have to be built new every time? If the latter, why ship icons that will be deleted and replaced anyway?

**Comment by rbuj** [comment]
build-png-icons generates the files that do not exist, and clean-png-icons was added to don't delete them manually.

**Comment by lukefromdc** [comment]
In a normal build of this, would a user (or distro) compiling from a clean tarball or clean copy of a git repo have any reason to build or clean icons? That is what I do not understand about this.

**Comment by rbuj** [comment]
Users and package maintainers don't need to run clean-png-icons and build-png-icons targets, as the png files must be reviewed.

**Comment by raveit65** [comment]
@rbuj @lukefromdc 
Can we consider this as a bug fix/improvement for 1.22 branch?
Or should we leave that for 1.24?

**Comment by raveit65** [comment]
I think it was really a good idea to regenerate icons.
Not 100% sure, because my eyes aren't the best, it seems that eg. the icon from nm-applet looks much better after a session restart under HIDPI resolution.
Well, it is blurred but not so broken than before.

**Comment by lukefromdc** [comment]
As long as we are shipping the new files and only generating at the user end those that are missing I have no objection to considering it a bugfix.

**Comment by rbuj** [comment]
I also agree that it's a bugfix.

**Comment by sc0w** [comment]
here, the icons are better without this PR (culprit commit https://github.com/mate-desktop/mate-icon-theme/commit/6712a9086e50603efb83f9e20fe08cccd830b05f)

screenshots taken from toolbar of pluma 1.22.1:

without https://github.com/mate-desktop/mate-icon-theme/commit/6712a9086e50603efb83f9e20fe08cccd830b05f:



with https://github.com/mate-desktop/mate-icon-theme/commit/6712a9086e50603efb83f9e20fe08cccd830b05f :



with this PR I see the icons blurry and weird

**Comment by raveit65** [comment]
With HIDPI resolutions the icons are looking sharp, but i agree that the dimensions of some icons are broken.
Bildschirmfoto zu 2019-08-20 14-33-31

**Comment by rbuj** [comment]
It seems that this issue only makes reference to 24x24 icons (HiDPI off).

24x24 icons don't exist in source files, we got this icon dimension by upscaling or downscaling from existing one (16x16, 22x22, 32x32, 48x48 or 256x256).

We can try to upsacale 22x22 to 24x24, for instance 24x24 actions icons:
```shell
cp mate/22x22/actions/Makefile.am mate/24x24/actions/Makefile.am
sed -i -e 's/-w=22 -h=22/-w=24 -h=24/g' mate/24x24/actions/Makefile.am
make -C mate/24x24/actions clean-png-icons build-png-icons
```

Captura de pantalla a 2019-08-20 14-42-18

Captura de Pantalla 2019-08-20 a les 14 45 41

Captura de Pantalla 2019-08-20 a les 14 45 56

**Comment by rbuj** [comment]
24x24 mimetypes icons have the same issue https://github.com/mate-desktop/mate-icon-theme/pull/43

**Comment by sc0w** [comment]
more screenshots, with eom 1.22.1 toolbar:

without https://github.com/mate-desktop/mate-icon-theme/commit/6712a9086e50603efb83f9e20fe08cccd830b05f:



with https://github.com/mate-desktop/mate-icon-theme/commit/6712a9086e50603efb83f9e20fe08cccd830b05f:

**Comment by rbuj** [comment]
To render all 24x24 icons from 22x22 svg sources.
```shell
$ cat do.sh 
dirs=()
for dir in $(find ./mate/24x24 -mindepth 1 -maxdepth 1 -type d); do
    directory=$(basename $dir)
    if [ -f "mate/22x22/$directory/Makefile.am" ]; \
    then
        cp mate/22x22/$directory/Makefile.am mate/24x24/$directory/Makefile.am
        sed -i -e 's/-w=22 -h=22/-w=24 -h=24/g' mate/24x24/$directory/Makefile.am
        dirs+=($directory)
    fi
done
./autogen.sh --prefix=/usr
for dir in ${dirs[@]}; do
    make -C mate/24x24/$dir clean-png-icons build-png-icons
done
```
Captura de pantalla a 2019-08-20 17-40-15

@sc0w - If you agree with these 24x24 icons I will open a new PR.

**Comment by rbuj** [comment]
New PR https://github.com/mate-desktop/mate-icon-theme/pull/44

**Pull request merged**
